# Generated by Django 4.0.3 on 2023-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='trip_choice',
            field=models.CharField(choices=[('one-way', 'One-Way'), ('round-trip', 'Round Trip')], default='one-way', max_length=10),
        ),
    ]
