# Generated by Django 4.0.3 on 2023-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0002_flight_trip_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_class_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_class_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_type',
            field=models.CharField(choices=[('economy', 'Economy Class'), ('business', 'Business Class')], default='economy', max_length=10),
        ),
    ]
