# Generated by Django 4.0.3 on 2023-06-07 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlineapp', '0007_admin_passenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={},
        ),
        migrations.AlterModelManagers(
            name='passenger',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='password',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='username',
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='passenger',
            table=None,
        ),
    ]
