# Generated by Django 4.0.3 on 2023-06-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0008_alter_passenger_options_alter_passenger_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
