# Generated by Django 4.0.3 on 2023-11-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0010_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='airport_code',
            field=models.CharField(default='CEB', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='airport_name',
            field=models.CharField(default='Mactan-Cebu International Airport', max_length=150),
        ),
    ]
