# Generated by Django 4.0.3 on 2023-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0012_alter_reservation_status_passengerreservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassengerReservation',
        ),
    ]
