# Generated by Django 4.0.3 on 2024-01-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0013_delete_passengerreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('last_login', models.CharField(max_length=100)),
                ('is_superuser', models.CharField(max_length=2)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('is_staff', models.CharField(max_length=2)),
                ('is_active', models.CharField(max_length=2)),
                ('data_joined', models.CharField(max_length=30)),
            ],
        ),
    ]
