# Generated by Django 4.0.3 on 2024-01-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlineapp', '0015_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
